[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish (Vite output)
  publish = "dist"
  
  # Environment variables
  [build.environment]
    NODE_VERSION = "18"

[build.processing]
  # Skip processing of JS/CSS for faster deploys
  skip_processing = false

# Headers for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Cross-Origin-Resource-Policy = "cross-origin"

# SPA redirect rule (fallback for client-side routing)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200